### ISSUE TITLE
Hardware used for training

### ISSUE THREAD

**Issue by bilalch193** [kentsommer/keras-posenet#2]
I recently came across posenet and tried to experiment with it. I modified the original architecture of posenet and now my input layer size is 1x100x224x224x3 where 1 is the batch size and 100 are the frames. Actually I have implemented lstm version of posenet. Now I have tried to run training on my own data, first on gtx750 and then on quadro k1200 4 GB gpu with tensorflow backend for keras(i am using posenet,written in keras) and also tried theano backend but everytime I get "out of memory" error. I want to ask what hardware specs your computer had on which you ran your training?

**Comment by kentsommer** [comment]
Sorry I must have missed this issue @TheRed002.

If you are using any sort of LSTM layers in this model your memory usage will grow significantly. 8GB minimum is probably necessary to use any LSTM layers. 

I used a TitanX, however, memory usage was under 6GB from what I can remember.
